# Generated by Django 4.2.8 on 2024-03-17 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybooks', '0003_status_user2book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user2book',
            old_name='isbn',
            new_name='google_id',
        ),
    ]
